cursor #f0dfd8
cursor_text_color #d7c2b9

foreground            #f0dfd8
background            #1a120e
selection_foreground  #432a1e
selection_background  #e6beac
url_color             #ffb693

color0   #1a120e
color1   #ff7872
color2   #97ff7f
color3   #ffe572
color4   #f29f77
color5   #76381a
color6   #ffb693
color7   #fff4ef
color8   #a59d99
color9   #ffa39f
color10  #b6ffa5
color11  #ffeea5
color12  #ffc0a3
color13  #ffcbb3
color14  #ffdece
color15  #fffaf8
