cursor #eedfe3
cursor_text_color #d4c2c8

foreground            #eedfe3
background            #181115
selection_foreground  #402a35
selection_background  #dfbdcc
url_color             #fcb0d6

color0   #181115
color1   #ff727b
color2   #9ffc7e
color3   #ffe172
color4   #ef98c4
color5   #743454
color6   #fcb0d6
color7   #ffeff7
color8   #a3979d
color9   #ff9fa5
color10  #bdffa5
color11  #ffeba5
color12  #ffbdde
color13  #ffc9e4
color14  #ffdced
color15  #fff8fb
