cursor #e1e2e9
cursor_text_color #c3c6cf

foreground            #e1e2e9
background            #111318
selection_foreground  #273141
selection_background  #bcc7dc
url_color             #a6c8ff

color0   #111318
color1   #ff729a
color2   #7fff91
color3   #fff872
color4   #8cb3f2
color5   #2a4776
color6   #a6c8ff
color7   #eff5ff
color8   #999ea5
color9   #ff9fba
color10  #a5ffb2
color11  #fffaa5
color12  #b3d0ff
color13  #c0d8ff
color14  #d6e6ff
color15  #f8fbff
