# 鼠标滚轮调节进度 (5秒跳动)
WHEEL_UP      seek 5
WHEEL_DOWN    seek -5
# 鼠标滚轮调节音量
WHEEL_UP      add volume 2
WHEEL_DOWN    add volume -2

# --- 扩展功能 ---
# 呼出文件浏览器 (大写 B)
B script-binding file_browser/browse-files
# 小写 b
b script-binding file_browser/browse-files
