[manager]
# 智能进入/打开
[[manager.prepend_keymap]]
on   = [ "l" ]
run  = "plugin smart-enter"
desc = "进入目录或使用默认程序打开文件"

[[manager.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin smart-enter"
desc = "进入目录或使用默认程序打开文件"

# 返回上一级
[[manager.prepend_keymap]]
on   = [ "h" ]
run  = "leave"
desc = "返回上一级目录"

# 帮助菜单 (覆盖默认的 ?)
[[manager.prepend_keymap]]
on   = [ "~" ]
run  = "help"
desc = "打开帮助菜单"

# 快速跳转快捷键 (Go to 系列)

[[manager.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd /mnt/data/03_Backup/ArchLinux/dotfiles"
desc = "跳转到 Dotfiles"

[[manager.prepend_keymap]]
on   = [ "g", "w" ]
run  = "cd ~/Pictures/wallpaper"
desc = "跳转到壁纸"

[[manager.prepend_keymap]]
on   = [ "g", "o" ]
run  = "cd /mnt/data/OneDrive"
desc = "跳转到 OneDrive"

[[manager.prepend_keymap]]
on   = [ "g", "c" ]
run  = "cd ~/.config"
desc = "跳转到配置目录"
